/*
 * Copyright 2019 Sergey Zolotarev
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char **argv)
{
  FILE *file;
  FILE *out_file;
  unsigned char c;
  int i;

  if (argc < 3) {
    fprintf(stderr, "Usage: cdump file var_name [out_file]\n");
    return EXIT_FAILURE;
  }

  if (argc >= 4) {
    out_file = fopen(argv[3], "w");
    if (out_file == NULL) {
      fprintf(stderr, "Could not open output file: %s\n", strerror(errno));
      return EXIT_FAILURE;
    }
  } else {
    out_file = stdout;
  }

  file = fopen(argv[1], "rb");
  if (file == NULL) {
    fprintf(stderr, "Could not open input file: %s\n", strerror(errno));
    return EXIT_FAILURE;
  }

  fprintf(out_file,
    "/* This file was automatically generated by cdump. DO NOT EDIT. */\n\n");
  fprintf(out_file, "static const char %s[] = {\n", argv[2]);

  i = 0;
  while ((fread(&c, sizeof(c), 1, file)) != 0) {
    if (i == 0) {
      fprintf(out_file, "\t\"");
    }
    fprintf(out_file, "\\x%02x", c);
    i += 4;
    if (i >= 68) {
      fputs("\"\n", out_file);
      i = 0;
    }
  }

  if (i != 0) {
    fputs("\"\n", out_file);
  }
  fprintf(out_file, "\n};\n");

  return EXIT_SUCCESS;
}
